/* eslint-disable @next/next/no-img-element */
import Head from "next/head";

import getStore from "store";
import { getPokemon } from "store/slices/pokemon";

import PokemonContainer from "@/components/home/PokemonContainer";
import ActionBar from "@/components/shared/actionBar";

function Home() {
  return (
    <main className="h-[100svh]">
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ActionBar />
      <PokemonContainer />
    </main>
  );
}

export async function getServerSideProps() {
  const store = getStore();
  await store.dispatch(getPokemon());
  return {
    props: {
      initialState: store.getState(),
    },
  };
}

export default Home;
