/* eslint-disable @next/next/no-img-element */
import { useSelector } from "react-redux";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import getStore from "store";
import {
  getPokemon,
  selectFilteredPokemon,
  selectLayout,
} from "store/slices/pokemon";

import ActionBar from "@/components/shared/actionBar";

function Home() {
  const pokemon = useSelector(selectFilteredPokemon);
  const layout = useSelector(selectLayout);

  return (
    <div className="p-4">
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ActionBar />
      <div className={`grid gap-4 ${layout === "grid" && "grid-cols-4"}`}>
        {pokemon.slice(0, 200).map((p: any) => (
          <Link
            href={`/pokemon/${p.id}`}
            key={p.id}
            className="grid cursor-pointer place-content-center justify-center gap-2 rounded-lg shadow-lg"
          >
            <Image
              alt={p.name}
              src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`}
              width={164}
              height={164}
              quality={55}
            />
            <h2>
              {p.id} - {p.name}
            </h2>
          </Link>
        ))}
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const store = getStore();
  await store.dispatch(getPokemon());
  return {
    props: {
      initialState: store.getState(),
    },
  };
}

export default Home;
