/* eslint-disable @next/next/no-img-element */
import { useDispatch, useSelector } from "react-redux";
import Head from "next/head";

import getStore from "store";
import {
  getPokemon,
  selectFilteredPokemon,
  selectSearch,
  setSearch,
} from "store/slices/pokemon";

function Home() {
  const dispatch = useDispatch();

  const pokemon = useSelector(selectFilteredPokemon);
  const search = useSelector(selectSearch);

  return (
    <div className="p-4">
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mb-8 flex">
        <h1 className="text-5xl">Pokemart</h1>
        <input
          type="text"
          value={search}
          onChange={(e) => {
            dispatch(setSearch(e.target.value));
          }}
          className="ml-auto rounded-md border p-2"
        />
      </div>
      <div className="grid grid-cols-4 gap-4">
        {pokemon.map((p: any) => (
          <div
            key={p.id}
            className="grid cursor-pointer place-content-center justify-center gap-2 rounded-lg shadow-md"
          >
            <img
              alt={p.name}
              src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${p.image}`}
              className="max-h-[200px]"
            />
            <h2>
              {p.id} - {p.name}
            </h2>
          </div>
        ))}
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const store = getStore();
  await store.dispatch(getPokemon());
  return {
    props: {
      initialState: store.getState(),
    },
  };
}

export default Home;
